### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by nicolasmure** [helios-ag/FMElfinderBundle#106]
Hi,

First of all, thanks for your bundle :+1: 
I'm using it with Symfony 2 for the server side and the original [ElFinder 2.1](https://github.com/Studio-42/elFinder) for the client side (with Angular JS).
I've configured your bundle like in your example : 
```yaml
# app/config/config.yml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple, 
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: %kernel.root_dir%/../web/userfiles
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
```
```yaml
# app/config/routing.yml
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
```
```yaml
# app/config/security.yml
security:
    access_control:
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
```

And I'm initializing the client part like this : 
```javascript
var elf = $('#elfinder').elfinder({
    lang: 'fr',             // language (OPTIONAL)
    url : 'http://my.symfony.root.url/efconnect',  // connector URL (REQUIRED)
    xhrFields: {
        withCredentials: true
    }
}).elfinder('instance'); 
```

I've also installed [NelmioCORSBundle](https://github.com/nelmio/NelmioCorsBundle) on my symfony project and setted it up like this : 
```yaml
# app/config/config.yml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/efconnect':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'X-Requested-With']
            allow_methods: ['POST', 'GET', 'PATCH', 'PUT', 'DELETE']
            max_age: 3600
            allow_credentials: true
```

The problem is that I'm having troubles when the client is requesting the server :
```
GET http://my.symfony.root.url/efconnect?cmd=open&target=&init=1&tree=1&_=1423215615264

Status 200 OK, Cross-Origin Request blocked.
```

Does this matters on your bundle?
Did I misconfigured something?
Even if I change nelmioCORS config as it : `allow_headers: ['*']`, the request is still blocked.

Any help is appreciated, if some users are in the same case than me, you're welcome to answer :wink: .
Tell me if I should ask on other used bundles rather than here,

Thank you :smiley:

**Comment by nicolasmure** [comment]
Hi,

After asking for help on [NelmioCORSBundle #41](https://github.com/nelmio/NelmioCorsBundle/issues/41), I think my problem is because of the `json_encode` and the `exit` calls made on [ElFinderConnector::output](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php#L119) function.
Please take a look to the link below to have more details.

Don't you think the elements used to build the final json should return something to the [ElFinderController::loadAction](https://github.com/helios-ag/FMElfinderBundle/blob/master/Controller/ElFinderController.php#L120) function? Doing so could be easier to hook and we could add and / or modify things before returning the json.

In my case, the SF cycle could go on and CORS headers could be activated.

What do you think of it?

**Comment by helios-ag** [comment]
Hi @nicolasmure well i see two possible ways to fix it, both will require minor changes to ElFinder lib, by removing exit() and moving some logic to loadAction (returning json), or by adding another "run()" (with other name) method to lib, that will be used by the bundle (i think this would be the best).

**Comment by nicolasmure** [comment]
Hi,
Thanks for your answer.
For the 2nd option, do you mean adding a field to `fm_elfinder instance` config (`app/config/config.yml`) to let the user configure which method to use (`run()` or a new  one) ? 
Then in the [`ElFinderLoader::load`](https://github.com/helios-ag/FMElfinderBundle/blob/master/Loader/ElFinderLoader.php#L54) function call the chosen method from the `config.yml` file ?
All these functions should return something if there are no `exit()` calls, to let the SF cycle ends and let other bundles handle data, right?

I saw you allow to create [custom loaders](https://github.com/helios-ag/FMElfinderBundle#custom-loader), would it be useful to allow to create custom [connectors](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php) ? May it do the trick?

Sorry if my comments are not adequate, I ain't got the whole bundle operation in mind :stuck_out_tongue:

**Comment by helios-ag** [comment]
>>For the 2nd option, do you mean adding a field to fm_elfinder instance config (app/config/config.yml) to let the user configure which method to use (run() or a new one) ? 
Yes, the option that will have default value as false (to be back compatible), called like "cors_support: "

>> I saw you allow to create custom loaders, would it be useful to allow to create custom connectors ? May it do the trick? 
You can override loader with custom "connector", bundle allow this to do without any difficulties. 

If everything will work fine, i would like to accept this PR!

**Comment by nicolasmure** [comment]
Yeah,
I've forked your repos and started to edit it to suit my needs. I haven't pushed it yet.
Can you tell me how can I run a build? I've started to add the option but then I changed my mind and I replaced the hard `exit` by `return` so data is returned through `loadAction`, who returns a [JsonResponse](http://api.symfony.com/2.4/Symfony/Component/HttpFoundation/JsonResponse.html). I would run a build to be sure it doesn't break BC.

I can push my modifications if you want.
You might tell me you would prefer an option in config file, I can do so if you don't agree with the first draw.
Thanks

**Comment by helios-ag** [comment]
Well, i think some people may use this bundle with their own modifications, and modifying existing function can break bundle or library behavior, that's why i suggest to move code to another function.

**Comment by nicolasmure** [comment]
Thank you for merging the related PR :smiley: 

As you suggested, here is a little integration guide : 

If you want to access to the connector URL from an other domain, simply configure FMElFindle bundle as you used to, and add the `cors_support: true` option to the cross domain istance : 
```yaml
# app/config/config.yml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            cors_support: true # allows cross domain requests handling
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple, 
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: /uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
```

Then you have to add the CORS headers (`Access-Control-Allow-Origin`) to the response. It can be easily done with [NelmioCORSBundle](https://github.com/nelmio/NelmioCorsBundle) : 

```yaml
# app/config/config.yml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/efconnect':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'X-Requested-With']
            allow_methods: ['POST', 'GET', 'PATCH', 'PUT', 'DELETE']
            max_age: 3600
            allow_credentials: true
```
