### ISSUE TITLE
Relative path option not works as expected

### ISSUE THREAD

**Issue by 1ed** [helios-ag/FMElfinderBundle#116]
These are the options I use:

```yaml
fm_elfinder:
    instances:
        default:
            locale: "%locale%"
            editor: ckeditor
            fullscreen: true
            relative_path: false
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/files
                        upload_allow: ['all']
                        upload_max_size: 2M

        images:
            locale: "%locale%"
            editor: ckeditor
            fullscreen: true
            relative_path: false
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

trsteel_ckeditor:
    language: "%locale%"
    filebrowser_browse_url:
        route: elfinder
    filebrowser_image_browse_url:
        route: elfinder
        route_parameters:
             instance: images
```
When I set the relative path option to `true` (which is the default) and I select an image, the path given back will be `images/filename.jpg` which is wrong. It should start with a `/` and should contain `uploads`. When I try to use the `alias` option the e.g. I add `alias: something` to the images section the result will be even worst `something/filename.jpg`. I think the root of the problem comes from upstream, as elfinder works with virtual paths in js... there was a similar issue there https://github.com/Studio-42/elFinder/issues/93 so maybe this is not the right place to fix it, but a solution would be I think if we always ask for absulute url and write some js to make it relative based on the request, something like `file.url.replace('{{ app.request.schemeAndHttpHost ~ app.request.baseUrl }}', '')`.
