### ISSUE TITLE
ElFinder and two or more instances with ckeditor

### ISSUE THREAD

**Issue by gaet** [helios-ag/FMElfinderBundle#117]
Hello,

I have two websites (siteweb & intranet) and I need to change the folder to upload documents with ivoryckeditor.

In my configuration, I have declare two instances of folder:

    ivory_ck_editor:
       default_config: default
       configs:
          default:
              filebrowserBrowseRoute: elfinder
              filebrowserBrowseRouteParameters:
                  instance: default

    fm_elfinder:
    #configuration_provider: my_elfinder_configurator
      instances:
        default: #site web
            locale: fr # defaults to current request locale
            editor: ckeditor # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            relative_path: %relative_path%
            #showhidden: false # defaults to false
            connector:
                debug: false # defaults to false
                plugin:
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion 
                        enable: true 
                        maxWidth: 750 
                        maxHeight: 750 
                        quality: 95 # JPEG image save quality
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: %dir_uploads%/siteweb
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/zip','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M
        intranet_equipes: #intranet
            locale: fr # defaults to current request locale
            editor: simple # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            relative_path: %relative_path%
            #showhidden: false # defaults to false
            connector:
                debug: false # defaults to false
                plugin:
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion 
                        enable: true 
                        maxWidth: 750 
                        maxHeight: 750 
                        quality: 95 # JPEG image save quality
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: %dir_uploads%/intranet/equipes
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/zip','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M

If I make  ->add('description', 'ckeditor') the 'default' is load and the website folder is open correctly.

But when I need to load intranet folder 'intranet_equipes', the folder open is always website 'default':

      $formMapper
            ->add('title')
            ->add('description', 'ckeditor', array(
                'config' => array(
                    'filebrowser_image_browse_url' => array(
                        'route'            => 'elfinder',
                        'route_parameters' => array('instance' => 'intranet_equipes'),
                    ),
                ),
            ))
            ->add('dateCreation')
        ;

I have delete  "filebrowserBrowseRouteParameters:  instance: default" too, but it's change nothing.

I think, my call is bad in my form but I don't see.
Do you have any ideas?

**Comment by helios-ag** [comment]
```yaml
 intranet_equipes: #intranet
        locale: fr # defaults to current request locale
        editor: simple # other choices are tinymce or simple, and form <-- should be ckeditor too
```
and does it open your folder if you aim browser to /elfinder/intranet_equipes ?

**Comment by gaet** [comment]
I have already try with "editor: ckeditor", but I have try again and it doesn't work.

If I try to open with the url /elfinder/default the 'siteweb' folder is open and with  /elfinder/intranet_equipes the 'equipes' folder is open, so with url all work fine.

**Comment by nicolasmure** [comment]
Hi,

Have you tried the following : 

```yaml
# app/config/config.yml
ivory_ck_editor:
    default_config: default
    configs:
      default:
          filebrowserBrowseRoute: elfinder
          filebrowserBrowseRouteParameters:
              instance: default
        # create a new configuration here :
        intranet_equipes:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: intranet_equipes
```
Then in your form builder use the `intranet_equipes` config :
```php
$builder->add('field', 'ckeditor', array(
    'config_name' => 'intranet_equipes',
));
```

And as helios-ag told you, be sure to set `editor: ckeditor` parameter to your elFinder `intranet_equipes` configuration.
