### ISSUE TITLE
showhidden: false !

### ISSUE THREAD

**Issue by xorgxx** [helios-ag/FMElfinderBundle#136]
hi i just install new symfony project all work well, but i have problem with : 
``` showhidden: false # defaults to false ``` if uncomment it block all ?
```fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
#            compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                debug: false # defaults to false
                roots:       #at least one root must be defined uploads
                    uploads1:
#                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: bundles/neocore/images #uploads
                        upload_allow: ['image/gif', 'image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
```
```
    configs:
#        my_config:
#            toolbar: standard

        default:
            extraPlugins: 'oembed,lineutils,widget' #
            toolbar: "neoToolbar_1" #   full - standard - basic

#            filebrowserBrowseRoute: elfinder
#            filebrowserBrowseRouteParameters:
#                instance: default #ckeditor
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instances: default
```
thank for your help 
config: symfony 2.6.6, ivoryckeditor master, and elfinder master
