### ISSUE TITLE
Issue with adding images to ckeditor

### ISSUE THREAD

**Issue by antonioperic** [helios-ag/FMElfinderBundle#148]
Hi, to all...
I have problem, when I try to add images to ckeditor with double click on image inside elfinder nothing happens except that elfinder open image in popup (some kind of preview)

**Comment by helios-ag** [comment]
Hi @antonioperic, what ckeditor bundle do you use? Have you set ckeditor as editor under this bundle configuration?

**Comment by antonioperic** [comment]
hi, here is my config:

    ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor

    fm_elfinder:
    connector:
        roots:       # at least one root must be defined
            uploads:
                path: media/elfinder
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                upload_max_size: 15M

**Comment by helios-ag** [comment]
Can you post full elfinder configuration?
Btw it should be like this:
```yaml
fm_elfinder:
  instances:
    default:
      locale: %locale%
      editor: ckeditor # other choices are tinymce or simple
      include_assets: true
      relative_path: true
      fullscreen: true
      connector:
          roots:       # at least one root must be defined
              uploads:
                  driver: LocalFileSystem
                  path: uploads
```
