### ISSUE TITLE
Error - Window does not connect folders

### ISSUE THREAD

**Issue by Bruno-Louvem** [helios-ag/FMElfinderBundle#158]
Hello friends.
I'm using the "ElfinderBundle" almost a year and suddenly it stopped working. It opens the screen but not connect to files and files.
I would like your help to solve this problem.

The error that symfony is returning is this:

Warning: Missing argument 1 for FM \ ElFinderPHP \ Connector \ ElFinderConnector :: run (), called in /var/www/mgtreinamento/vendor/helios-ag/fm-elfinder-bundle/Loader/ElFinderLoader.php on line 58 and defined

The version of my "ElfinderBundle" is 3.4 and this is my file "config.yml".

```yml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            relative_path: false
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined

                    uploads:

                        driver: LocalFileSystem

                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

                        url: /uploads
        ckeditor:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            relative_path: false
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined

                    uploads:

                        driver: LocalFileSystem

                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

                        url: /uploads
        form:
            locale: %locale% # defaults to current request locale
            editor: form # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

                        url: /uploads
```
![Image of Error](http://mgtreinamento.com.br/error-elfinder.png)

I use it in conjunction with the ckeditor and common forms.
This error screen happened in a form, but is also occurring in ckeditor

```php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('categoria','entity',array(
                'class'=> 'AdminBundle:Categoria',
                'property' => 'nome',
                'label'=>'Categoria do curso',
                'label_attr' => array('class' => 'col-sm-2 control-label'),
                'attr'       => array('class' => 'form-control'),
                'required'=>false
            ))
            ->add('imagem','elfinder', array(
                'instance'=>'default',
                'enable'=>true,
                'label'=>'Imagem do curso',
                'label_attr' => array('class' => 'col-sm-2 control-label'),
                'attr'       => array('class' => 'form-control'),
                'required'=>false
            ));
    }
```
I would appreciate your help'm no idea what can be.

**Comment by helios-ag** [comment]
Look at issue https://github.com/helios-ag/ElFinderPHP/issues/22#issuecomment-132481039
PS. i will update deps on holidays.

**Comment by Bruno-Louvem** [comment]
Then just update the bundle by the composer?
What I do not understand is that I was working and suddenly stopped.
I will try today evening make this update, because I have a deploy to do this weekend and do not want to bring this error to the production environment.
Thank you very much helios-ag.

**Comment by nicolasmure** [comment]
Yes, updating should fix it.
Maybe you've updated your app dependencies and didn't noticed it has also updated elfinder bundle?

**Comment by Bruno-Louvem** [comment]
No, the "ElFinderBundle" I have this in version 3.4, will update it to latest version.
Do you know if I have to change something in config.yml with this update?

**Comment by Bruno-Louvem** [comment]
Hello nicolasmure your solution worked. this new version of Bundle I realized that the elfinder This returning the file path with two '/', for example '// uploads / path / file '.
But at least it now returned to work.
Thank you all

**Comment by wassimjahid** [comment]
Hello @Bruno-Louvem, I have the same problem.
Can you explain to me your solution with the two '/'?

**Comment by Bruno-Louvem** [comment]
Hello wassimjahid, I solved the problem of the '\\' with this setting:
path_prefix '' in instance.
```yaml
fm_elfinder:
    instances:
        form:
            locale: %locale% 
            editor: form 
            fullscreen: true 
            include_assets: true 
            relative_path: true
            path_prefix: '' #<----HERE
            connector:
                debug: false
                roots:       
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg' , 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 8M

                        url: /uploads
```
PS .: Sorry for the delay of the answer, maybe you have already solved, but it can help others.
