### ISSUE TITLE
Accepted configuration for "attributes" under "roots" is incorrect

### ISSUE THREAD

**Issue by jstnthms** [helios-ag/FMElfinderBundle#188]
The bundle allows `attributes` to be defined like this:

```
fm_elfinder:
    instances:
        default:
            # ...
            connector:
                # ...
                roots:
                    uploads:
                        # ...
                        attributes:
                            pattern: '/(.*?)/'
                            read: true
                            write: false
                            locked: true
```

Where `attributes` ends up being an array with keys "pattern", "read", "write" and "locked".

However, if you look at https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#general-usage-example, you'll see that `attributes` is actually expected to be an array of arrays. So, the accepted configuration should look something like this:

```
fm_elfinder:
    instances:
        default:
            # ...
            connector:
                # ...
                roots:
                    uploads:
                        # ...
                        attributes:
                            - pattern: '/(.*?)/'
                              read: true
                              write: false
                              locked: true
```

I ended up manually configuring `attributes` in my own bundle in order to produce the proper format, after which the attributes were successfully applied in the Elfinder file browser.

I'm not exactly sure how the Treebuilder should be changed, but I imagine it's something like this:

```
->arrayNode('attributes')
    ->prototype('array')
        ->children()
            ->scalarNode('pattern')->end()
            ->scalarNode('read')->end()
            ->scalarNode('write')->end()
            ->scalarNode('locked')->end()
            ->scalarNode('hidden')->end()
        ->end()
    ->end()
    ->defaultValue(array())
->end()
```
