### ISSUE TITLE
Expand "elfinder" type

### ISSUE THREAD

**Issue by jstnthms** [helios-ag/FMElfinderBundle#200]
It would be cleaner if we could setup any elfinder instance through the "elfinder" form type.

If I had config that looked like this:

```
fm_elfinder:
    # ...
    instances:
        # ...
        form:
            # ...
            editor: form
        wysiwyg:
            # ...
            editor: tinymce4
```

I could initialize form fields like this:

```
$builder
    ->add('banner', 'elfinder', array(
        'instance' => 'form',
    ))
    ->add('body', 'elfinder', array(
        'instance' => 'wysiwyg',
    ))
;
```

and the widget would be implied from the editor associated with the instance. (ie. `form` editor means create a textfield, `tinymce4` editor means create a textarea, etc.)

Then, instead of making sure I have:

```
{{ elfinder_tinymce_init4('wysiwyg') }}
{{ tinymce_init() }}
```

in all of the appropriate templates, it would be done automatically with the widget. (Like is currently done with the "elfinder" type.)
## 

Further, there could exist a master javascript file that knows how to initialize all the different elfinder widgets. The inputs could simply be given some expected markup like the following:

```
<input type="text"
    data-elfinder-id="unique-id"
    data-elfinder-instance="form"
    data-elfinder-homefolder />
```

and initialization would happen as long as the master javascript file was included on the page.
## 

Is this something can could be done without breaking a lot of existing code?
