### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by lucasaba** [helios-ag/FMElfinderBundle#236]
##### Issue Type:

 - Bug Report

##### Bundle Version:

6.1

##### Summary:

File extension is not displayed and neither is passed to the editor. I'm not sure is a FMElfinder problem or not...I'm using amazon's S3  service with Flysystem.

##### Steps To Reproduce:

This is my configuration:

```
fm_elfinder:
    instances:
        default:
            editor: ckeditor
            include_assets: true
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg']
            relative_path: false
            connector:
                roots:       
                    aws_s3:
                        driver: Flysystem
                        url: "https://s3-%aws_s3_region%.amazonaws.com/%aws_s3_bucket_name%"
                        flysystem:
                            type: aws_s3_v3
                            options:
                                aws_s3_v3:
                                    key: "%aws_s3_key%"
                                    secret: "%aws_s3_secret%"
                                    region: "%aws_s3_region%"
                                    version: latest
                                    bucket_name: "%aws_s3_bucket_name%"
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
```

When the file browser pops up I can see all files correctly but their extension is not visibile:

![schermata del 2016-04-22 16-19-34](https://cloud.githubusercontent.com/assets/206325/14744214/20487c5c-08a6-11e6-9878-6124ed05fd18.png)

Whe I double click on the image, extension is not passed. The shown URL is "https://s3-eu-west-1.amazonaws.com/mtimgarticoli/test/firmaikaboardita". If I manually add the extension, everything works perfectly.

##### Expected Results:

I'd expect the file extension to be present

##### Actual Results:

The file extension is not present.
