### ISSUE TITLE
Special characters in filename not allowing to upload files

### ISSUE THREAD

**Issue by dipens** [helios-ag/FMElfinderBundle#239]
##### Issue Type:

Bug Report

##### Bundle Version:

6

##### Summary:

While uploading a file which contains some special characters like #, $, !, etc, it give me an error saying Invalid File name.

##### Steps To Reproduce:

Config is same as #228 .
The web server is on Ubuntu and the directory which is the root for the bundle is a mapped drive to a Windows File Server (not sure if that matters).

Whenever I try to upload a file which contains special characters like #, $, !, etc, it give me an error saying 

> Invalid File name.

![capture](https://cloud.githubusercontent.com/assets/7505804/14866346/49518a5a-0c91-11e6-800d-b5a434aaf67d.PNG)

My `config.yml`
```
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: /var/www/html/Project/web/W3Files/
                        upload_allow: ['all']
                        upload_deny: []
                        upload_max_size: 500M
```

The only thing I could find related to this was [this](https://github.com/Studio-42/elFinder/issues/601) but I am not sure how to use this. Not sure if this has been asked before but I couldn't find anything else. What am I doing wrong here?

##### Expected Results:

File should have been uploaded properly.

##### Actual Results:

Gave me an error saying 
> Invalid File name.

**Comment by dipens** [comment]
Hello @helios-ag  can you please look into this when you have time?

**Comment by helios-ag** [comment]
Hi @dipens , this error triggered is because default option 'accepted_name' differs from default in elfinder.
Change it to yours under uploads node of your configuration, sorry for delay.
```yaml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        accepted_name: '/^[^\.].*/'   #<<< this is default
                        driver: LocalFileSystem
                        path: /var/www/html/Project/web/W3Files/
                        upload_allow: ['all']
                        upload_deny: []
                        upload_max_size: 500M
```
