### ISSUE TITLE
Plugin Sanitizer won't work.

### ISSUE THREAD

**Issue by jorismulliez** [helios-ag/FMElfinderBundle#248]
Hi all,

First thanks for your work, this bundle is easy to use (except for my problem below ;) )

##### Issue Type:

Please pick one and delete the rest:
 - Bug Report

##### Bundle Version:

v6 (I don't know the exact version : my composer.json : `"helios-ag/fm-elfinder-bundle": "~6"`)

##### Summary:

I'm trying to use the plugin "sanitizer" and I can't get any result...

##### Steps To Reproduce:

Here is my configuration in config.yml

```yml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            include_assets: true
            connector:
                bind:
                    upload.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    mkdir.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    mkfile.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    rename.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    archive.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    ls.pre:
                        - Plugin.Sanitizer.cmdPreprocess
                    ls:
                        - Plugin.Sanitizer.cmdPostprocess
                    upload.presave:
                        - Plugin.Sanitizer.onUpLoadPreSave
                plugin:
                    Sanitizer:
                        enable: true
                        targets: ['(',')','[',']','{','}','\','/',':','*','?','"','<','>','|',' ','''','à','á','â','ã','ä','ç','è','é','ê','ë','ì','í','î','ï','ñ','ò','ó','ô','õ','ö','ù','ú','û','ü','ý','ÿ','À','Á','Â','Ã','Ä','Ç','È','É','Ê','Ë','Ì','Í','Î','Ï','Ñ','Ò','Ó','Ô','Õ','Ö','Ù','Ú','Û','Ü','Ý']
                        replace: '_'
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/wysiwyg
                        upload_allow:
                            - 'image/png'
                            - 'image/jpg'
                            - 'image/jpeg'
                            - 'application/pdf'
                            - 'application/zip'
                            - 'application/vnd.oasis.opendocument.text'                                   # .odt
                            - 'application/vnd.oasis.opendocument.spreadsheet'                            # .ods
                            - 'application/vnd.oasis.opendocument.presentation'                           # .odp
                            - 'application/vnd.ms-excel'                                                  # .xls
                            - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'         # .xlsx
                            - 'application/vnd.ms-powerpoint'                                             # .ppt
                            - 'application/vnd.openxmlformats-officedocument.presentationml.presentation' # .pptx
                            - 'application/msword'                                                        # .doc
                            - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'   # .docx
                        upload_deny: ['all']
                        upload_max_size: 10M # also file upload sizes restricted in php.ini
```

And I can't get any results or indication that the plugin is working...
I tried to debug into the plugin itself (dump() or die())... my debug code wasn't reached.
I tried also to reduce the configuration to just enable plugin and just one "bind" (mkdir.pre), but no result too...

Note : the configuration I tried is based on the comments on this file : https://github.com/Studio-42/elFinder/blob/2.1-src/php/plugins/Sanitizer/plugin.php

##### Expected Results:

I want that all file/dir created/uploaded with elfinder to be "sanitize" (no special chars, accents, etc...)

##### Actual Results:

Nothing :)

Thanks for your help,
