### ISSUE TITLE
Quarantine configuration option invalid.

### ISSUE THREAD

**Issue by dbergunder** [helios-ag/FMElfinderBundle#256]
##### Issue Type:
- Bug Report
##### Bundle Version:

5.3
##### Summary:

According to the [docs](https://github.com/helios-ag/FMElfinderBundle#add-configuration-options-to-your-configyml), we can set the [quarantine path](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#quarantine) in the configuration.  It's entirely possible I'm not configuring it correctly, but I couldn't find any examples online or in the repo.  I think I can achieve this if I [override the configurator](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/advanced-configuration.md#custom-configuration-provider).

```
#app/config/config.yml
fm_elfinder:
    instances:
        default:
            connector:
                roots:
                    uploads:
                        quarantine: %kernel.cache_dir%/elfinder
```

Q: Why bother moving the quarantine folder?  
A: Due to permissions conflict, the quarantine folder is interfering with Capistrano deployments (we have a separate deployment user) which means we have to directly reset permissions on the uploads directory as sudo.
##### Expected Results:

The .quarantine folder to move to the cache dir.
##### Actual Results:

InvalidConfigurationException in ArrayNode.php line 317

```
Unrecognized option "quarantine" under "fm_elfinder.instances.default.connector.roots.uploads"
```
