### ISSUE TITLE
srcset possible?

### ISSUE THREAD

**Issue by benblub** [helios-ag/FMElfinderBundle#264]
Wanted use srcset, is there a way to generate srcsets after upload Images?

tried with autoresize to generate more then 1 Image but it resized only the orginal pic.

```
resize1:
                  driver: LocalFileSystem
                  path: uploads
                  plugins:
                      AutoResize:
                          enable: true # For control by volume driver
                          maxWidth: 800 # Path to Water mark image
                          maxHeight: 800 # Margin right pixel
                          quality: 95 # JPEG image save quality
                  upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                  upload_deny: ['all']
                  upload_max_size: 2M
```

**Comment by helios-ag** [comment]
I think it don't possible with this plugins, only by overriding/adding own ones.

**Comment by benblub** [comment]
ok will try DI with your Events. i Post here my solution.

**Comment by helios-ag** [comment]
Would be great!

**Comment by benblub** [comment]
Ok i wrote a little Plugin which do the job.
https://github.com/benblub/ElFinder-Thumbnail-Plugin

Its not finished yet, update Code the days. (works very basicly)

**Comment by benblub** [comment]
Code updated

Would be nice if you add the Plugin to the Connector Branch.

**Comment by benblub** [comment]
Want adding Styles / Classes with CKEditor, tried global

```
ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: [ [ "Bold", "-", "BulletedList", "-", "Link", "-", "Unlink", "-", "Image" , "-", "Maximize" ] ]
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: default
                bodyClass:
                    enterMode: CKEDITOR.ENTER_DIV
    styles:
        my_styles:
            - { name: "CSS Style", element: "div", attributes: { class: "my_style" }}
            - { name: "CSS Style", element: "p", attributes: { class: "my_style" }}
            - { name: "CSS Style", element: "img", attributes: { class: "my_style" }}
```

or in the Form Type directly

```
'config' => array(
                    'stylesSet' => 'my_styles',
                    'filebrowserBrowseRoute' => 'elfinder',
                    'filebrowserBrowseRouteParameters' => array(
                        'instance' => 'default',
                        'homeFolder' => ''
                    ),
                ),
                'styles' => array(
                    'my_styles' => array(
                        array('name' => 'CSS Style', 'element' => 'img', 'attributes' => array('class' => 'my_style')),
                    )),
```

both want work and ideas?

**Comment by helios-ag** [comment]
Never used custom styles, but i think you should set `styleSet` option
```yaml
#config.yml
...
ivory_ck_editor:
    default_config: default
    configs:
        default:
            stylesSet: "my_styles" #<<<
...
```
