### ISSUE TITLE
Service as Driver, Driver not found

### ISSUE THREAD

**Issue by samanmohamadi** [helios-ag/FMElfinderBundle#267]
##### Issue Type:
- Bug Report
##### Bundle Version:

 6.2.1
##### Summary:

using service as volume driver throws this error:
`Driver \"FM\\ElFinderPHP\\Driver\\ElFinderVolumecmf_media.adapter.elfinder.phpcr_driver\" does not exists`
##### Steps To Reproduce:

```
fm_elfinder:
    instances:
        default:
            locale: "%locale%"
            editor: ckeditor
            connector:
                roots:
                    media:
                        driver: cmf_media.adapter.elfinder.phpcr_driver
```
