### ISSUE TITLE
Configure Elfinder Bundle to connect with a MySQL database

### ISSUE THREAD

**Issue by nouridev** [helios-ag/FMElfinderBundle#300]
I get problem to connect elfinder with my MySQL database, I changed the driver : 'LocalFileSystem' to` driver : 'MySQL', and i configured the configuration of my database in Driver\ElFinderVolumeMySQL, but it steel not working, i get this error "Invalid backend configuration. Readable volumes not available."

Can you help me please to solve this problem ???

**Comment by helios-ag** [comment]
@nouridev can you post full configration of elfinder bundle, and what version of symfony and bundle do you use.

**Comment by CoreAptics** [comment]
I have the same error, i'm using Symfony 3.4.4 and FMElfinderBundle 6.2.1, my config: 
```
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        form:
            locale: %locale% # defaults to current request locale
            editor: form # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            connector:
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        alias: Fichiers
                        driver: MySQL
                        path: uploads
                        upload_allow: ['all']
                        upload_max_size: 128M # also file upload sizes restricted in php.ini
```
And I had to overwrite the class because it didn't respect the abstract class ElFinderVolumeDriver. Where can I find a doc for MySQLDriver ?

Differents parts of the class i had to change: 

I needed to this function:
```
public function _chmod($path, $mode)
    {
        parent::__chmod($path, $mode);
    }
```

I needed to had $jpgQuality option:
```
public function resize($hash, $width, $height, $x, $y, $mode = 'resize', $bg = '', $degree = 0, $jpgQuality = null) {
		if ($this->commandDisabled('resize')) {
			return $this->setError(ElFinder::ERROR_PERM_DENIED);
		}
		
		if (($file = $this->file($hash)) == false) {
			return $this->setError(ElFinder::ERROR_FILE_NOT_FOUND);
		}
               /** ... **/
}
```

I needed to had $hash option:
```
public function search($q, $mimes, $hash = null) {
		$result = array();
                /** ... **/
}
```

Tanks a lot !

**Comment by helios-ag** [comment]
@CoreAptics, @nouridev  hi
You can try to use `dev` branch (it's synced with latest elfinder (2.1.32), and uses original elfinder repo as php lib) for mysql support with following configuration
```yaml
        default:
            locale: "%locale%"
            editor: form # other choices are tinymce or simple
            include_assets: true
            relative_path: true
            connector:
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false
                        driver: MySQL
                        mysql_settings:
                            user: 'root'
                            password: 'root'
                            db: 'elfinder'
                            host: 'localhost'
                        path: 1
```
