### ISSUE TITLE
Unable to find template "FMElfinderBundle:Form:elfinder_widget.html.twig" 

### ISSUE THREAD

**Issue by bhtomming** [helios-ag/FMElfinderBundle#306]
##### Issue Type:

Please pick one and delete the rest:
 - Bug Report
 - Feature Idea
 - Documentation Report

##### Bundle Version:

Master or exact version, i.e. 6.0.1

##### Summary:

Please explain the problem briefly.

##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

You can also paste gist.github.com links for larger files.

Please don't paste configuration screenshots, instead use gist/pastebin/etc 
or directly paste configuration into issue behind github flavored markdown tags for code

##### Expected Results:

What did you expect to happen when running the steps above?

##### Actual Results:

What actually happened?

```
(Paste verbatim command output here)
```

**Comment by helios-ag** [comment]
Hi @bhtomming, can you upgrade to 7.x?
7.0.1 Has corrected paths for twig templates.

**Comment by NodokaMurmevent** [comment]
hello i have the same problem : 
i have PHP 7.2.5

conf files : 
```yml
fm_elfinder:    
    instances:
        default:
            editor: tinymce4
            locale: "%locale%"
            include_assets: true
            relative_path: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 32M 
```

```yml
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        simple:
            theme: "modern"
            file_browser_callback : elFinderBrowser
```

my template twig
```twig
{% block external_javascripts %}
    {{ elfinder_tinymce_init4('default') }}
    {{ tinymce_init() }}
{% endblock %}

```
composer.json
```json
    "require": {
        "php": "^7.1.3",
        "helios-ag/fm-elfinder-bundle": "^8.0",

        "stfalcon/tinymce-bundle": "^2.3"
  
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "component-dir": "web/assets"
    },

```
