### ISSUE TITLE
Public link from dropbox volume

### ISSUE THREAD

**Issue by flohw** [helios-ag/FMElfinderBundle#324]
##### Issue Type:

question

##### Bundle Version:

8.0.3

##### Summary:

I can't get the icon to mount a dropbox volume available. I was able to automount a dropbox volume (which is good and better than expected) but I can't get the public link of my files within my dropbox volume. I have a link based on the path in my dropbox but with my domain : `http://localhost/Public/my-pic.jpg` i.e.
It seems that elfinder thinks it's a local flysystem driver as the icon prepresenting the volume is `img/volume_icon_local.png` instead of `img/volume_icon_dropbox.png`

##### Steps To Reproduce:

Here is my configuration:
```yaml
fm_elfinder:
    assets_path: /bundles
    instances:
        default:
            locale: '%locale%'
            editor: ckeditor
            include_assets: true
            connector:
                roots:
                    dropbox:
                        driver: Flysystem
                        flysystem:
                            type: dropbox
                            options:
                                dropbox:
                                    app: not-relevant ?
                                    token: my-token
                        upload_allow:
                            - some/mime-types
                        upload_max_size: 80M
```

##### Expected Results:

The icon to mount a dropbox volume or the button "get public link" in the info box.

##### Actual Results:

None of both expected result.

Additionally the bundle seems to be outdated with flysystem dropbox adapter. It should use the one provided by https://github.com/spatie/flysystem-dropbox as the actual from https://github.com/thephpleague/flysystem-dropbox is abandonned.
