### ISSUE TITLE
How can I set privateKey for Flysystem ftp(sftp)

### ISSUE THREAD

**Issue by l396635210** [helios-ag/FMElfinderBundle#332]
##### Issue Type:

Please pick one and delete the rest:
 - Feature Idea
 - Documentation Report

##### Bundle Version:

Master

##### Summary:

I wang to connect to my assets server by sftp authKey but, not work well.
How can i config or do some thing

my config file
```
fm_elfinder:
  instances:
    default:
      include_assets: true
      relative_path: true
      connector:
        roots:
          uploads:
            driver: LocalFileSystem
            path: uploads
    sftp:
      include_assets: true
      relative_path: true
      connector:
        roots:
          uploads:
            driver: Flysystem
            url: 'http://%env(resolve:ASSETS_HOST)%'
            tmb_url: '/%env(resolve:TMB_PATH)%'
            tmb_path: '%env(resolve:TMB_PATH)%'
            flysystem:
              type: ftp
              options:
                ftp:
                  sftp: true
                  host: '%env(resolve:ASSETS_HOST)%'
                  port: 22
                  username: assets
                  password: '@Assets1314'
                  privateKey: '/home/assets/.ssh/id_rsa'
                  root: '/opt/www/%env(resolve:ASSETS_HOST)%'
```
