### ISSUE TITLE
Trash Volume does not get deleted files

### ISSUE THREAD

**Issue by jrabahiClaraVista** [helios-ag/FMElfinderBundle#399]
Hello,

Great bundle, I have integrated it in a symfony4 project and connected it To a s3 bucket on AWS. It works but I add to do a few research and configuration to make it works properly (adding a reload parameter to the elconnect route in order to get up to date content to simulate the refresh clic).
I set up the thumbnail system as well.

Now I'm trying to make the trash volume working here is my configuration (yaml) :

```yaml
connector:
                roots:
                    bucket:
                        driver: Flysystem  
                        alias: Volume 1                                                                 
                        url: '%env(s3_url)%/%env(brand_folder)%/%env(user_folder)%'
                        flysystem:
                            type: aws_s3_v3
                            options:
                                aws_s3_v3:
                                    key: '%env(s3_key)%'
                                    secret: '%env(s3_secret)%'
                                    bucket_name: '%env(s3_bucket_name)%'
                                    region: '%env(s3_region)%'
                                    version: latest
                        path: '%env(brand_folder)%/%env(user_folder)%'
                        tmb_path: '%env(brand_folder)%/.tmb'
                        tmb_url: '%env(brand_folder)%/.tmb'
                        upload_deny: ['all']                                                              
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'text/plain']  
                        upload_order: ['deny','allow']                                                      
                        img_lib: gd
                        trash_hash: t1_XA
                    trash:
                        volume_id: 1
                        driver: Trash
                        alias: Trash
                        url: '%env(brand_folder)%/.trash'
                        path: '%env(brand_folder)%/.trash'
                        tmb_path: '%env(brand_folder)%/.tmb'
                        tmb_url: '%env(brand_folder)%/.tmb'
                        upload_deny: ['all']
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'text/plain']
                        upload_order: ['deny', 'allow']
                        show_hidden: true
```

But impossible to get any deleted files in the trash volume to restaure them. I am not sure of is the trash_hash option value, I put the value of the Trash hash volume.
Did you ever use the Trash configuration ?

Best regards.
