### ISSUE TITLE
Can't install assets

### ISSUE THREAD

**Issue by lalamimhamed** [helios-ag/FMElfinderBundle#401]
Hi,
During the installation, the fm_elfinder.yaml file is not created automatically, so I created it and configure it like that:
```
fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: fr
            editor: ckeditor
            fullscreen: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/medias
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', ]
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
```
After that, I tried to install assets, but I got this exception in my terminal:
```
In FileLoader.php line 173:

  There is no extension able to load the configuration for "fm_elfinder" (in
  "D:\Projets\training\config/packages/fm_elfinder.yaml"). Looked for namespa
  ce "fm_elfinder", found ""framework", "twig", "twig_extra", "web_profiler",
   "monolog", "debug", "sensio_framework_extra", "doctrine", "doctrine_migrat
  ions", "security", "maker", "stof_doctrine_extensions", "knp_paginator", "f
  os_ck_editor"" in D:\Projets\training\config/packages/fm_elfinder.yaml (whi
  ch is loaded in resource "D:\Projets\training\config/packages/fm_elfinder.y
  aml").


In YamlFileLoader.php line 713:

  There is no extension able to load the configuration for "fm_elfinder" (in
  "D:\Projets\training\config/packages/fm_elfinder.yaml"). Looked for namespa
  ce "fm_elfinder", found ""framework", "twig", "twig_extra", "web_profiler",
   "monolog", "debug", "sensio_framework_extra", "doctrine", "doctrine_migrat
  ions", "security", "maker", "stof_doctrine_extensions", "knp_paginator", "f
  os_ck_editor"".
```
Like the previous versions, I can't find components folder in my project. And I'm using Symfony 5.
Any suggestion?
