### ISSUE TITLE
Multiple file selection

### ISSUE THREAD

**Issue by davtyanadam** [helios-ag/FMElfinderBundle#419]
Loving this bundle, but one of the most important (at least to me) features of elfinder, the multiple file selection is missing.
It would be nice if we could enable/disable it from the fm_elfinder.yaml

Thanks in advance ;)

**Comment by blindpenguin** [comment]
I guess it's about selecting multiple files in the form type. It's in the docs for elFinder itself. I could use this functionality too, but i'm not entirely sure how to activate it in this bundle.

https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commandsOptions

**Comment by helios-ag** [comment]
This has been implemented in `main` by PR #566

### Configuration

Multiple selection can be enabled for an entire elFinder instance:

```yaml
fm_elfinder:
    instances:
        form:
            editor: form
            multiple: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: '%kernel.project_dir%/public/uploads'
                        url: /uploads
```

It can also be enabled or overridden for an individual `ElFinderType` field:

```php
use FM\ElfinderBundle\Form\Type\ElFinderType;

$builder->add('images', ElFinderType::class, [
    'instance' => 'form',
    'multiple' => true,
]);
```

### Behavior

When multiple selection is enabled:

- the form model contains an `array<string>` of selected URLs;
- the input stores the selection as a JSON array;
- selection order is preserved;
- malformed JSON and non-string array entries produce a form transformation error.

When `multiple` is disabled, the existing scalar string behavior is preserved for backward compatibility.

### Custom callbacks

Custom integrations can use the new `callback` editor:

```yaml
fm_elfinder:
    instances:
        media_picker:
            editor: callback
            callback_function: App.media.onSelect
            multiple: true
```

The configured JavaScript callback receives an array of selected file objects containing `url`, `name`, `mime`, `size`, and `hash`.

### Upgrade step

After upgrading, republish the bundle assets:

```bash
bin/console elfinder:install
bin/console assets:install
```

This issue can now be closed as completed.
