### ISSUE TITLE
ElFinderType in EasyAdmin 4.x (with Symfony 6.x) form shows only a text field

### ISSUE THREAD

**Issue by Baloobear** [helios-ag/FMElfinderBundle#472]
Hello everyone.

**Describe the bug**

When I try to integrate a form field of the type **ElFinderType** in my EasyAdmin crud controller I only get a simple text field without any function. 

Even trying to integrate the infos related to https://stackoverflow.com/questions/64480120/using-elfinder-on-symfony-i-cant-select-images or #406 (incl. overwriting the templates and converting the given infos to the updated EasyAdmin 3.x/4.x configuration) does not help in any way. It also seems that the widget template (neither the original one or the own in `templates/bundles/FMElFinderBundle/Form`) seems not to be used.

**To Reproduce**

Here's the code I'm using:

_CrudController_

```php
// ProjectCrudController.php
// ...
public function configureFields(string $pageName): iterable
{
    // ...
    yield Field::new('introImage', 'Intro Image')
        ->setFormType(ElFinderType::class)
        ->setFormTypeOptions([
            'instance' => 'projects_default',
            'enable' => true,
        ])
        ->onlyOnForms()
    ;
    // ...
}
```

_fm_elfinder.yaml_

```yaml
fm_elfinder:
    instances:
        projects_default:
            locale: 'de'
            editor: form
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg']
            connector:
                roots:
                    projects:
                        driver: LocalFileSystem
                        path: images/projects
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_max_size: 5M
```

**Additional context**

Used packages/libs:
* Symfony 6.0.2
* EasyAdmin 4.0.2

Any help is appreciated.

Kind regards,
Dennis
