### ISSUE TITLE
Invalid backend response since 12.3

### ISSUE THREAD

**Issue by olia-bn** [helios-ag/FMElfinderBundle#504]
**Describe the bug**
Upgrading from `12.2.3` to `^12.3` (currently `12.3` and `12.3.1`) causes "Invalid backend response" when accessing the connector.

**To Reproduce**
Config is pretty stock, PHP 8.1.12 but happens on 8.2 as well. 
```
fm_elfinder:
    instances:
        default:
            editor: form
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
```

**(OPTIONAL) Additional context**
Other people reported the issue in the last 2 weeks but closed it after finding the workaround: enabling [CORS support](https://github.com/helios-ag/FMElfinderBundle/blob/main/docs/cors-support.md) makes the problem dissapear.

But that's a workaround, not a fix (and potential security risk): I am accessing the connector URL from the same domain on the client side.
