### ISSUE TITLE
Impossible to upload

### ISSUE THREAD

**Issue by mreichstadt** [helios-ag/FMElfinderBundle#513]
Hi,
I have a problem when using your bundle.
When I try to upload a file I get a blank page with "ERR_TOO_MANY_REDIRECTS".
I followed your READM so I don't know what I could do. 
Could you help me please?

Here are my files:
![image](https://github.com/helios-ag/FMElfinderBundle/assets/14784435/f6b54ace-5421-4289-b2fb-8797829bd577)
![image](https://github.com/helios-ag/FMElfinderBundle/assets/14784435/92e74a3d-d285-435c-90dd-621e816a8052)
![image](https://github.com/helios-ag/FMElfinderBundle/assets/14784435/053a2689-731e-4829-a6c3-fb26f0e7bd15)
![image](https://github.com/helios-ag/FMElfinderBundle/assets/14784435/dcf39294-1c2b-4e5b-a36e-020ff8cbec97)
![image](https://github.com/helios-ag/FMElfinderBundle/assets/14784435/daac3453-26d7-44b9-a8bd-ba312d18d994)

Thank you in advance

**Comment by helios-ag** [comment]
hi @mreichstadt 
Some points that I have spotted: when@test and configuration of access_control must be placed in regular place

descriptif field name in the builder, try to add config section as described here https://github.com/helios-ag/FMElfinderBundle/blob/main/docs/ckeditor-integration.md

**Comment by helios-ag** [comment]
In most cases redirect loop coming from improper security configuration.
here is example from my old project
```yaml
    fos_ck_editor:
        default_config: my_config
        configs:
            my_config:
                allowedContent: true
                filebrowserBrowseRoute: elfinder
                filebrowserBrowseRouteParameters:
                    instance: ckeditor
```

```yaml
#security.yaml
    role_hierarchy:
        ROLE_API: ROLE_USER
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
```
