### ISSUE TITLE
When using Flysystem driver with custom type you need to pass `options` key

### ISSUE THREAD

**Issue by JohJohan** [helios-ag/FMElfinderBundle#528]
**Describe the bug**
I want to use the `custom` type for `flysystem` to use an already existing flysystem adapter but i didn't set `options` key as this is also not used only required for parameter. 

**To Reproduce**
You should have the following config:
```yaml
fm_elfinder:
  instances:
    default:
      connector:
        roots:
          aws_s3:
            flysystem:
              type: custom
              adapter_service: 'app.flysystem.public_adapter'
#              options:
```

As you can see `options` is commented out

**(OPTIONAL) Additional context**
You will get the following error: `Warning: Undefined array key "options"` on `vendor/helios-ag/fm-elfinder-bundle/src/Configuration/ElFinderConfigurationReader.php:77`

I would suggest setting default empty array for `options` so you dont run into this issue when you dont have `options` set.
