### ISSUE TITLE
unable to add symfony service as a volume driver

### ISSUE THREAD

**Issue by linasm83** [helios-ag/FMElfinderBundle#79]
Hi,

My config:

``` yaml
fm_elfinder:
    instances:
        default_phpcr:
            connector:
                roots:
                    media:
                        driver: cmf_media.adapter.elfinder.phpcr_driver
```

Getting the error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                                                             
  Invalid configuration for path "fm_elfinder.instances.default_phpcr.connector.roots.media.driver": Invalid filesystem driver ""cmf_media.adapter.elfinder.phpcr_driver"" 
```

So it looks like it doesn't pass configuration validation in _DependencyInjection\Configuration_:

```
->scalarNode('driver')
    ->isRequired()
    ->validate()
    ->ifNotInArray(array('LocalFileSystem', 'FTP', 'FTPIIS', 'Dropbox', 'S3'))
       ->thenInvalid('Invalid filesystem driver "%s"')
    ->end()
```

If i'm not missing something then there's no way to implement custom driver at the moment until this validation exists or it is not altered in some way (issue exists only in version 2.*)
